stages:
  - build
  - deploy

before_script:
  - docker info
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" 

build:
  stage: build
  script:
    - docker build -t matchmaker .
    - docker tag matchmaker parthmehrotra/matchmaker
    
deploy:
  stage: deploy
  script:
    - docker push parthmehrotra/matchmaker
